---
title: "Workshop"
output: 
  html_document:
    includes: 
      in_header: 
      - hero-image.html
---


### [2021 International Methodology Symposium](https://www.statcan.gc.ca/eng/conferences/symposium2021/index)

Date: Thursday, October 14th
Time: 10:00am -- 2:00pm ET


Survey estimation is the bread-and-butter of many statistical agencies. As technological and statistical advances provide both new data sources and new modeling techniques, estimation procedures must adapt to accommodate these advances. Effectively combining data collected under a complex sampling design with new sources of auxiliary data has the potential to greatly increase the efficiency of our estimators.  Luckily, how to best leverage these multiple data sources has been a vibrant area of recent survey research.


This workshop will introduce participants to one modern, model-assisted approach to survey estimation, where predictive models serve as the key link between the survey data and auxiliary data.  This method will cover a broad class of predictive models, including generalized linear models, regularized (elastic net) regression, and regression trees.  The workshop will also include demonstrations of how to fit these estimators using the statistical software `R`. Prior `R` experience is encouraged but not required.  


[This `R` script](https://mcconvil.github.io/IMS21_ML_Surveys/mase_R.R) contains all the code used in the XXX slide deck.
